# Generated by Django 4.2.27 on 2026-02-04 16:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[("gt", ">"), ("lt", "<"), ("eq", "=")], max_length=20
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("resolved_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("ack", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alerts.alertrule",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["factory", "is_active"], name="alerts_aler_factory_3f6893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["factory", "metric_name"], name="alerts_aler_factory_bd8bbc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertrule",
            unique_together={("factory", "name")},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["factory", "status", "triggered_at"],
                name="alerts_aler_factory_4366cb_idx",
            ),
        ),
    ]
