# Generated by Django 4.2.27 on 2026-02-03 17:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("device_type", models.CharField(max_length=100)),
                ("last_seen_at", models.DateTimeField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("payload", models.JSONField()),
                (
                    "idempotency_key",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["factory", "timestamp"],
                        name="devices_eve_factory_ccbdee_idx",
                    ),
                    models.Index(
                        fields=["device", "timestamp"],
                        name="devices_eve_device__536e1f_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="devices_eve_event_t_86589b_idx",
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="devices_eve_idempot_3f7247_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["factory", "is_active"], name="devices_dev_factory_0d76f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_id"], name="devices_dev_device__e2c19e_idx"
            ),
        ),
    ]
