# Generated by Django 4.2.27 on 2026-02-03 17:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("timezone", models.CharField(default="Asia/Dhaka", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("capacity_per_hour", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.factory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "skill_level",
                    models.IntegerField(
                        choices=[
                            (1, "Trainee"),
                            (2, "Junior"),
                            (3, "Senior"),
                            (4, "Expert"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operators",
                        to="core.factory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("machine_type", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="core.line",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="factory",
            index=models.Index(fields=["code", "is_active"], name="core_factor_code_dd72bb_idx"),
        ),
        migrations.AddIndex(
            model_name="operator",
            index=models.Index(
                fields=["factory", "is_active"], name="core_operat_factory_1e34be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operator",
            index=models.Index(fields=["employee_id"], name="core_operat_employe_965e63_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["line", "is_active"], name="core_machin_line_id_e41561_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="machine",
            unique_together={("line", "code")},
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(
                fields=["factory", "is_active"], name="core_line_factory_39e095_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("factory", "code")},
        ),
    ]
