# Generated by Django 4.2.27 on 2026-02-04 16:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DowntimeReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DowntimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(null=True)),
                ("duration_minutes", models.IntegerField(null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.machine"
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.downtimereason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["factory", "is_active"],
                        name="monitoring__factory_4da932_idx",
                    )
                ],
                "unique_together": {("factory", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="downtimereason",
            index=models.Index(
                fields=["factory", "is_active"], name="monitoring__factory_65cd86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downtimereason",
            index=models.Index(
                fields=["factory", "category"], name="monitoring__factory_1827ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="downtimereason",
            unique_together={("factory", "code")},
        ),
        migrations.AddIndex(
            model_name="downtimelog",
            index=models.Index(
                fields=["factory", "started_at"], name="monitoring__factory_8eb924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downtimelog",
            index=models.Index(
                fields=["machine", "started_at"], name="monitoring__machine_7c4e7c_idx"
            ),
        ),
    ]
