# Generated by Django 4.2.27 on 2026-02-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("total_production", models.IntegerField(default=0)),
                ("target_production", models.IntegerField(default=0)),
                (
                    "efficiency_percent",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("uptime_minutes", models.IntegerField(default=0)),
                ("downtime_minutes", models.IntegerField(default=0)),
                ("defect_count", models.IntegerField(default=0)),
                (
                    "cycle_time_avg_seconds",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.factory"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.line",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.operator",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.shift",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["factory", "snapshot_date"],
                        name="analytics_k_factory_b632a8_idx",
                    ),
                    models.Index(
                        fields=["line", "snapshot_date"],
                        name="analytics_k_line_id_c1201a_idx",
                    ),
                    models.Index(
                        fields=["machine", "snapshot_date"],
                        name="analytics_k_machine_f435e0_idx",
                    ),
                ],
                "unique_together": {
                    ("factory", "line", "machine", "operator", "snapshot_date", "shift")
                },
            },
        ),
    ]
